version: '3.7'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 9080:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
  adminer:
    image: adminer
    restart: always
    ports:
      - 9081:8080